name: yalla_mazra3a
description: A villa rental app for the MENA region.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  provider: ^6.0.5

  # UI components
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.5.0
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
        - assets/logo.png
        - assets/google_logo.png
        - assets/bg.png
        - assets/splash_logo.png
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit