import '../models/villa.dart';

class MockData {
  static List<Villa> getVillas() {
    return [
      Villa(
        id: '1',
        title: 'مزرعة الأحلام',
        description: 'مزرعة فاخرة مع مسبح خاص وإطلالة رائعة على الطبيعة. تتميز بالخصوصية التامة وتصميم داخلي أنيق. مثالية للعائلات والاجتماعات الخاصة. تتضمن مسبح كبير، وحديقة واسعة، ومنطقة شواء، وجلسات خارجية مظللة. تحتوي على غرف نوم واسعة مع حمامات خاصة. المطبخ مجهز بالكامل مع جميع الأدوات اللازمة للطهي.',
        price: 1200,
        location: 'الرياض - حي الملقا',
        images: [
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.8,
        bedroomsCount: 4,
        bathroomsCount: 3,
        capacity: 10,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'تكييف مركزي', 'تراس'],
        ownerName: 'سلطان العتيبي',
        ownerPhone: '0501234567',
      ),
      Villa(
        id: '2',
        title: 'استراحة النخيل',
        description: 'استراحة راقية محاطة بأشجار النخيل، توفر أجواء هادئة ومريحة بعيدًا عن صخب المدينة. تتميز بمسبح كبير وحديقة خضراء واسعة. تحتوي على غرف نوم مريحة مع إطلالات جميلة. المطبخ مجهز بالكامل مع جميع المستلزمات. تتوفر منطقة شواء وجلسات خارجية مظللة للاستمتاع بالهواء الطلق.',
        price: 850,
        location: 'الرياض - حي الياسمين',
        images: [
          'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1613977257363-707ba9348227?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.6,
        bedroomsCount: 3,
        bathroomsCount: 2,
        capacity: 8,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'تكييف'],
        ownerName: 'خالد السعيد',
        ownerPhone: '0551234567',
      ),
      Villa(
        id: '3',
        title: 'شاليه البحيرة',
        description: 'شاليه فاخر يطل على بحيرة اصطناعية جميلة، مصمم بأسلوب عصري وأنيق. يوفر إقامة مريحة مع مناظر طبيعية خلابة. المسبح الخاص يتيح للضيوف الاستمتاع بالسباحة في أجواء خاصة. يحتوي على غرف نوم واسعة مع أسرة مريحة وحمامات حديثة. الصالة الواسعة مثالية للاجتماعات العائلية والمناسبات الخاصة.',
        price: 1500,
        location: 'جدة - أبحر الشمالية',
        images: [
          'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.9,
        bedroomsCount: 5,
        bathroomsCount: 4,
        capacity: 12,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'ألعاب أطفال', 'تكييف مركزي', 'جاكوزي'],
        ownerName: 'عبدالله الغامدي',
        ownerPhone: '0561234567',
      ),
      Villa(
        id: '4',
        title: 'مزرعة الواحة',
        description: 'مزرعة هادئة تقع في منطقة ريفية جميلة، تحيط بها المساحات الخضراء والنباتات المتنوعة. توفر المزرعة إقامة مريحة مع مرافق ترفيهية متكاملة. تتميز بحديقة واسعة وجلسات خارجية مظللة. المسبح الخاص يتيح للضيوف الاسترخاء والاستمتاع بالطقس الجميل. تشمل غرف نوم مريحة ومطبخ مجهز بالكامل.',
        price: 750,
        location: 'الرياض - الدرعية',
        images: [
          'https://images.unsplash.com/photo-1506126279646-a697353d3166?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1598228723793-52759bba239c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTc4fHx2aWxsYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1580237072353-751a8a5b9fea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjE2fHx2aWxsYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.4,
        bedroomsCount: 3,
        bathroomsCount: 2,
        capacity: 8,
        hasPool: true,
        hasWifi: false,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'ملعب أطفال'],
        ownerName: 'فهد القحطاني',
        ownerPhone: '0541234567',
      ),
      Villa(
        id: '5',
        title: 'فيلا المنتزه',
        description: 'فيلا عصرية تقع في منطقة راقية، تتميز بتصميم داخلي أنيق ومساحات واسعة. توفر إقامة فاخرة مع جميع وسائل الراحة الحديثة. تحتوي على مسبح خاص وحديقة جميلة. الغرف واسعة ومضاءة بشكل جيد مع إطلالات رائعة. المطبخ مجهز بأحدث الأجهزة والأدوات. تتوفر منطقة ترفيهية داخلية تشمل ألعاب متنوعة.',
        price: 1800,
        location: 'الخبر - حي الأندلس',
        images: [
          'https://images.unsplash.com/photo-1580237541049-2d715a09486e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTF8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1598228723793-52759bba239c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTc4fHx2aWxsYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1518780664697-55e3ad937233?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjI2fHx2aWxsYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.7,
        bedroomsCount: 6,
        bathroomsCount: 5,
        capacity: 15,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'غرفة ألعاب', 'تكييف مركزي', 'جاكوزي', 'ساونا'],
        ownerName: 'محمد العمري',
        ownerPhone: '0581234567',
      ),
      Villa(
        id: '6',
        title: 'استراحة الريف',
        description: 'استراحة ريفية جميلة تقع وسط الطبيعة الخلابة، توفر أجواء هادئة ومريحة بعيدًا عن ضوضاء المدينة. تتميز بمساحات خضراء واسعة وإطلالات طبيعية رائعة. تحتوي على مسبح خاص ومنطقة شواء مجهزة. الغرف مصممة بأسلوب ريفي أنيق مع جميع وسائل الراحة اللازمة. المطبخ بسيط ومجهز بالمستلزمات الأساسية.',
        price: 600,
        location: 'أبها - السودة',
        images: [
          'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTR8fHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1606402179428-a57976d71fa4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA0fHx2aWxsYXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.3,
        bedroomsCount: 2,
        bathroomsCount: 1,
        capacity: 6,
        hasPool: false,
        hasWifi: false,
        hasBarbecue: true,
        amenities: ['مطبخ', 'موقف سيارات', 'إطلالة جبلية'],
        ownerName: 'أحمد الشهري',
        ownerPhone: '0531234567',
      ),
      Villa(
        id: '7',
        title: 'شاليه الساحل',
        description: 'شاليه ساحلي مميز يطل مباشرة على البحر، يوفر إطلالات رائعة وإقامة مريحة. تتميز بتصميم عصري أنيق مستوحى من الطابع البحري. المسبح الخاص يطل على البحر مباشرة. تحتوي على شرفة واسعة مع جلسات خارجية للاستمتاع بالمنظر. الغرف مضاءة بشكل جيد ومصممة بألوان منعشة. المطبخ مجهز بالكامل مع إطلالة على البحر.',
        price: 2000,
        location: 'الدمام - شاطئ نصف القمر',
        images: [
          'https://images.unsplash.com/photo-1523217582562-09d0def993a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.8,
        bedroomsCount: 4,
        bathroomsCount: 3,
        capacity: 10,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'إطلالة بحرية', 'تكييف مركزي', 'وصول مباشر للشاطئ'],
        ownerName: 'سعد البحري',
        ownerPhone: '0591234567',
      ),
      Villa(
        id: '8',
        title: 'فيلا الحدائق',
        description: 'فيلا فاخرة تحيط بها الحدائق الغناء من جميع الجهات، توفر واحة من الهدوء والجمال الطبيعي. تتميز بتصميم معماري فريد ومساحات داخلية واسعة. المسبح الكبير يتوسط الحديقة مع منطقة استرخاء محيطة به. تحتوي على غرف فسيحة ذات إطلالات خضراء. الصالة الرئيسية تطل على الحديقة من خلال نوافذ كبيرة. المطبخ حديث ومجهز بأفضل الأجهزة.',
        price: 1600,
        location: 'الرياض - حي الورود',
        images: [
          'https://images.unsplash.com/photo-1543465646-c08aca2fd29e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzB8fGx1eHVyeSUyMGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTd8fGx1eHVyeSUyMGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1503174971373-b1f69a8429dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGx1eHVyeSUyMHZpbGxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.7,
        bedroomsCount: 5,
        bathroomsCount: 4,
        capacity: 12,
        hasPool: true,
        hasWifi: true,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'حديقة واسعة', 'تكييف مركزي', 'غرفة سينما', 'صالة رياضية'],
        ownerName: 'ناصر الشمري',
        ownerPhone: '0571234567',
      ),
      Villa(
        id: '9',
        title: 'استراحة الصحراء',
        description: 'استراحة مميزة تقع على حافة الصحراء، تجمع بين الراحة العصرية وسحر الطبيعة الصحراوية. تتميز بتصميم يحاكي الطابع التراثي مع لمسات عصرية. توفر إطلالات رائعة على الكثبان الرملية. تحتوي على مسبح خاص ومنطقة جلوس خارجية للاستمتاع بالنجوم ليلاً. الغرف مريحة ومكيفة مع ديكورات مستوحاة من البيئة المحلية.',
        price: 900,
        location: 'الرياض - الثمامة',
        images: [
          'https://images.unsplash.com/photo-1562610744-7c4d0962d9d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVzZXJ0JTIwaG91c2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1587066308595-fb05789b9295?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGRlc2VydCUyMGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1593604572577-1c6c44fa2804?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fGRlc2VydCUyMGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.5,
        bedroomsCount: 3,
        bathroomsCount: 2,
        capacity: 8,
        hasPool: true,
        hasWifi: false,
        hasBarbecue: true,
        amenities: ['مطبخ كامل', 'موقف سيارات', 'جلسة خارجية', 'تكييف', 'موقد للتدفئة'],
        ownerName: 'محمد العنزي',
        ownerPhone: '0511234567',
      ),
      Villa(
        id: '10',
        title: 'مزرعة الينابيع',
        description: 'مزرعة خلابة تتميز بوجود ينابيع طبيعية ومساحات خضراء واسعة. توفر تجربة فريدة للاسترخاء والاستمتاع بالطبيعة. تحتوي على مسبح يغذى من المياه الطبيعية ومنطقة شواء مظللة. الغرف مصممة بأسلوب ريفي جذاب مع إطلالات على المساحات الخضراء. المطبخ بسيط ومجهز بالأدوات الأساسية. تتوفر أنشطة متنوعة مثل ركوب الخيل والمشي لمسافات طويلة.',
        price: 700,
        location: 'الباحة - بني ظبيان',
        images: [
          'https://images.unsplash.com/photo-1622015663319-e97e697503ee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZmFybWhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1558442074-3c19857bc1dc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZmFybWhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
          'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60',
        ],
        rating: 4.4,
        bedroomsCount: 2,
        bathroomsCount: 2,
        capacity: 6,
        hasPool: true,
        hasWifi: false,
        hasBarbecue: true,
        amenities: ['مطبخ', 'موقف سيارات', 'إطلالة على الجبال', 'ينابيع طبيعية'],
        ownerName: 'عبدالرحمن الزهراني',
        ownerPhone: '0521234567',
      ),
    ];
  }
}
